# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  audit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [25.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - &install-dependencies
        name: Install dependencies
        run: npm ci
      - name: Audit dependencies
        run: npm audit

  format:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [25.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - *install-dependencies
      - name: Check formatting
        run: npm run pretty:check

  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [25.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - *install-dependencies
      - name: Validate schemas
        run: npm run validate:all

  typecheck:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [25.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - *install-dependencies
      - name: Typecheck
        run: npm run typecheck
